### ISSUE TITLE
PartitionError: App partition "ota_0" is too small for micropython app

### ISSUE THREAD

**Issue by fwebcc** [glenn20/mp-image-tool-esp32#4]
root@ESPMicroPython:/opt/mp-image-tool-esp32# ./mp-image-tool-esp32 /opt/FWEBCC/ESP32_V21_20240730.bin --table ota
Running mp-image-tool-esp32 0.0.4 (Python 3.10.7).
Opening image file: /opt/FWEBCC/ESP32_V21_20240730.bin...
Firmware Chip type: esp32
Firmware Flash size: 4MB
Micropython App size: 0x1a2180 bytes (1,672 KB)
Partition table (flash size: 4MB):
# Name             Type     SubType      Offset       Size        End Flags           
  nvs              data     nvs          0x9000     0x6000     0xf000   0x0  (24.0 kB)
  phy_init         data     phy          0xf000     0x1000    0x10000   0x0   (4.0 kB)
  factory          app      factory     0x10000   0x1f0000   0x200000   0x0   (1.9 MB)
  vfs              data     fat        0x200000   0x200000   0x400000   0x0   (2.0 MB)
Micropython app fills 84.3% of factory partition (311 kB free)
PartitionError: App partition "ota_0" is too small for micropython app (0x1a2180 bytes).

**Comment by glenn20** [comment]
For 4MB devices, micropython sets the default app partition size for OTA enabled devices to 1,572,864 (0x180,000) bytes, which is smaller than the default. Compare [partitions-4MiB-ota.csv](https://github.com/micropython/micropython/blob/master/ports/esp32/partitions-4MiB-ota.csv) to [partitions-4MiB.csv](https://github.com/micropython/micropython/blob/master/ports/esp32/partitions-4MiB.csv). It also disables some micropython features so that the micropython app binary will fit in the smaller partition. `mp-image-tool-esp32` uses the default app partition sizes adopted by micropython, but you can override that.

You have two options:

1. Increase the size of the OTA app partitions to accommodate a full micropython app binary (which means less space available for your filesystem), OR
1. Use a firmware that has been compiled with some features removed to make is smaller.

Generally, I use option 1 as none of my use cases needs a lot of filesystem storage and means you can OTA update from any standard micropython `.app-bin` file.

## Option 1:

```bash
./mp-image-tool-esp32 /opt/FWEBCC/ESP32_V21_20240730.bin --table ota -a 0x1f0000
```

or 

```bash
./mp-image-tool-esp32 /opt/FWEBCC/ESP32_V21_20240730.bin --table ota -a 0x1b0000
```

if you want a little less headroom for your OTA firmware files and a little more space in your filesystem.

**Comment by glenn20** [comment]
Thanks for the report - I have added "Use the '-a' option to set a larger app partition size." to the error message. I thought about automatically increasing the partition sizes if the app is too big, but decided it would be better if peaople understood the trade-offs involved.

**Comment by glenn20** [comment]
If you feel the issue is not resolved, please feel free to re-open or add any more comments or questions.
